title: "flutter 雑記帳"
summary: "個人で学んだことをまとめた雑記帳です。"
topics: ["flutter", "dart"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 1_introduce
  - 2_class
  - 3_variables_functions

